---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-datadir
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: oci-bv